### ISSUE TITLE
undefined reference error

### ISSUE THREAD

**Issue by ava6969** [RustingSword/tensorboard_logger#11]
Hi I am struggling to get this running . i have followed this steps

1) clone repo
2) make
3) included directories in my cmake files
4) tried adding .a file to local and .a file to cmakelist file

/usr/bin/ld: /home/dewe/CLionProjects/FastDRL/utilities/logger.cpp:93: undefined reference to `TensorBoardLogger::add_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)'
/usr/bin/ld: /home/dewe/CLionProjects/FastDRL/utilities/logger.cpp:94: undefined reference to `TensorBoardLogger::add_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)'
/usr/bin/ld: /home/dewe/CLionProjects/FastDRL/utilities/logger.cpp:95: undefined reference to `TensorBoardLogger::add_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)'
/usr/bin/ld: CMakeFiles/FastDRL.dir/utilities/logger.cpp.o: in function `Logger::~Logger()':

**Comment by RustingSword** [comment]
Seems the linker can not find the lib. Do you have other libs? Maybe you can put the .a file along with them if they can be found correctly.

Also I tried a simple CMake config which successfully compiles (although didn't run, cause the relative path of the `assets` dir is wrong), relative to root dir of this project:
```bash
> cat CMakeLists.txt
cmake_minimum_required(VERSION 3.13.4)

add_subdirectory(tests)

> cat tests/CMakeLists.txt
cmake_minimum_required(VERSION 3.13.4)

set (CMAKE_CXX_STANDARD 11)
include_directories (
    ../include
    /usr/local/include
)

link_directories (
    ..
    /usr/local/lib
)

add_executable(test_lib test_tensorboard_logger.cc)
target_link_libraries(test_lib tensorboard_logger protobuf pthread)
```

**Comment by ava6969** [comment]
thanks i just retried, all is was missing was adding protobuf and pthread to the target_link_libraries
