### ISSUE TITLE
Multiple scalars in single plot

### ISSUE THREAD

**Issue by ihmc3jn09hk** [RustingSword/tensorboard_logger#12]
Thanks for the work. Its great and handy.

Is there a way to print multiple scalars in single plot ?

[Example](https://i.stack.imgur.com/aRES4.png)

**Comment by RustingSword** [comment]
Thanks for your interest.

According to my experience, these two lines should correspond to two different runs (directories) of the same metric (tag), like this:

![image](https://user-images.githubusercontent.com/449233/131966651-766f33a5-1250-4534-89c9-76fbe9549280.png)

TensorBoard will display them in the same plot for convenient comparison.

**Comment by ihmc3jn09hk** [comment]
> Thanks for your interest.
> 
> According to my experience, these two lines should correspond to two different runs (directories) of the same metric (tag), like this:
> 
> ![image](https://user-images.githubusercontent.com/449233/131966651-766f33a5-1250-4534-89c9-76fbe9549280.png)
> 
> TensorBoard will display them in the same plot for convenient comparison.

I see. Great thx for the info.
