### ISSUE TITLE
Data flushed on every write

### ISSUE THREAD

**Issue by jakkes** [RustingSword/tensorboard_logger#14]
I noticed in src that data is flushed on every event. Could this be controlled (like in tensorboard clients in pytorch/tensorflow) to happen only every Nth write and/or timeout?

**Comment by RustingSword** [comment]
Is this to reduce IO overhead? It is possible to add a counter/timer to control the flush frequency, at the cost of a stale log file. But I think logging operations will not be called very frequently, thus the overhead is negligible compared to other IO heavy operations.

**Comment by RustingSword** [comment]
I think If you use a large batch size, or the metrics vary rapidly, then frequent logging is reasonable. Even in this situation, scalar logging should be quite lightweight an operation. On the other hand, histograms should be logged less frequently.
