### ISSUE TITLE
Resuming from a previous run

### ISSUE THREAD

**Issue by tuero** [RustingSword/tensorboard_logger#18]
I'm currently using this project as a way to track metrics during ML training. Since training can take long, I have a way which can save/store models/data as a checkpoint during an exit call, and will reload that to resume training. It would also be nice if metrics can continue to track rather than starting from scratch. 

Would this be a useful feature to add? Currently, I've changed the constructor as the following (for my personal use)
```c++
// Header of TensorBoardLogger
// ofs_ = new std::ofstream(log_file, std::ios::out | std::ios::trunc | std::ios::binary);
ofs_ = new std::ofstream(log_file, std::ios::out | std::ios::app | std::ios::binary);
```
Adding this feature would be a quick change. Maybe have a resume flag as a default argument set false in the header for `TensorBoardLogger`? If this something that would be welcomed, I could make a PR.

**Comment by RustingSword** [comment]
Thanks and this is surely welcomed! I think it's a nice feature, and a resume flag is appropriate.

I have a small concern that, as discussed in #13, in the future the event file name may be auto generated. However when resuming from a previous file, the file name should be given by the user. How to make these two features compatible can be left to future.

**Comment by tuero** [comment]
Closing as #19 implements this.
