### ISSUE TITLE
add image with raw pixel data

### ISSUE THREAD

**Issue by Mirocos** [RustingSword/tensorboard_logger#20]
Hi, I read all  codes in the test file that I actually didn't find an example to save images with its raw pixel data.
Does it already supported or not?

**Comment by RustingSword** [comment]
Not yet, it has to be encoded into one of the [supported formats](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/summary.proto#L102) first.

**Comment by Mirocos** [comment]
Hi, I was trying to encode raw pixels data to png format and send it to `add_image`.
My code looks like below:
```c++
            int out_len = 0;
            int width = t.size(0), height = t.size(1), channel = t.size(2);
            auto encoded_bytes = stbi_write_png_to_mem((const unsigned char*)v.data(), 0, height, width, channel, &out_len);
            std::string png(encoded_bytes, encoded_bytes+out_len);
            logger.add_image("Tensor raw data plugin", 1, png, height, width, channel, "imrod");
            std::ofstream file("./demo/imord.png", std::ios::binary);
            file << png;
```

where `stbi_write_png_to_mem` is a function from `stbi_image project`,.

I found that the `imord.png` is correct which ouput by the binary stream. But the file output by the logger, say `imrod.pb` seems to be wrong. Because tensorboard tell that no dashboard active data in it.

**Comment by RustingSword** [comment]
Thanks for the feedback, I will try to look into this as soon as possible. Maybe you can do a quick inspection to do a round trip by `stbi_load(some_valid_png_file)` then `stbi_write_png_to_mem` to see what's wrong. If this works, then the diff comes from the raw pixel data; if this doesn't work, maybe stbi encodes png file differently?

**Comment by RustingSword** [comment]
I just tried this, and it worked:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b99ba57..7b885d0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,3 +23,7 @@ target_link_libraries(tensorboard_logger PUBLIC ${Protobuf_LIBRARIES})

 add_executable(tensorboard_logger_test tests/test_tensorboard_logger.cc)
 target_link_libraries(tensorboard_logger_test tensorboard_logger)
+target_include_directories(tensorboard_logger_test PUBLIC
+    ../stb/deprecated/
+    ../stb/
+)
diff --git a/tests/test_tensorboard_logger.cc b/tests/test_tensorboard_logger.cc
index d9f1f3e..bde9d07 100644
--- a/tests/test_tensorboard_logger.cc
+++ b/tests/test_tensorboard_logger.cc
@@ -5,6 +5,14 @@
 #include <vector>

 #include "tensorboard_logger.h"
+#define STB_IMAGE_WRITE_IMPLEMENTATION
+#include "stb_image_write.h"
+
+#define STB_IMAGE_IMPLEMENTATION
+#include "stb_image.h"
+
+#define STB_DEFINE
+#include "stb.h"

 using namespace std;

@@ -57,6 +65,21 @@ int test_log_image(TensorBoardLogger& logger) {
     logger.add_image("TensorBoard Audo Plugin", 1, image2, 1766, 814, 3,
                      "TensorBoard", "Audio");

+    // add image from memory
+    int x, y, c, size;
+    const char* test_file = "tux.png";
+    auto image3 = stbi_load(test_file, &x, &y, &c, 0);
+    auto encoded = stbi_write_png_to_mem(image3, 0, x, y, c, &size);
+    cout << test_file << " x=" << x << " y=" << y << " c=" << c <<
+        " re-encoded size=" << size << endl;
+    string png(encoded, encoded + size);
+    logger.add_image("image from memory", 1, png, x, y, c, "Tux");
+    ofstream file("reencoded_tux.png", ios::binary);
+    file << png;
+    file.close();
+    stbi_image_free(image3);
+    STBIW_FREE(encoded);
+
     // add multiple images
     // FIXME This seems doesn't work anymore.
     // logger.add_images(
```
<img width="756" alt="image" src="https://user-images.githubusercontent.com/449233/164873414-b414bdf9-9272-4c3b-b1db-7112eacacff8.png">

Test file is this one https://cdn.freebiesupply.com/logos/large/2x/tux-logo-png-transparent.png

**Comment by Mirocos** [comment]
Hi, thanks for that check. I use the reference picture `tux.png` and load it first than write it to encoded memory. I don't what happened that I open the target `imrod.pb` in hex format and all I saw is like below snap.
![image](https://user-images.githubusercontent.com/39593790/164882686-9141916b-e7c8-4156-8547-33eaab994cfa.png)

**Comment by Mirocos** [comment]
I know what happened why tensorboard didn't detect the event file. From this issue #13, I found that my target ouput filename did not have a substring like `tfevents` that is what tensorboard seach for. Sorry to waste your time, my apologies

**Comment by RustingSword** [comment]
🤦 I'm planning to add a warning message if the file name is not valid.

**Comment by Mirocos** [comment]
What about assert if the filename does not have substring "tfevents"?

**Comment by RustingSword** [comment]
Yes, on second thought I think throwing a `runtime_error` is more appropriate than a warning message. Just pushed the code, thanks for the suggestion.
