### ISSUE TITLE
ofs_ is created with new but not deleted

### ISSUE THREAD

**Issue by Kait0** [RustingSword/tensorboard_logger#26]
The file system stream ofs_ in [tensorboard_logger.h](https://github.com/RustingSword/tensorboard_logger/blob/c92ede4b3b7d9571696e384bf7ec948b0f3eb77d/include/tensorboard_logger.h#L64) is created with new.
There is however no delete in the [destructor](https://github.com/RustingSword/tensorboard_logger/blob/c92ede4b3b7d9571696e384bf7ec948b0f3eb77d/include/tensorboard_logger.h#L76) leading to a memory leak.

Should be easy to fix by adding `delete ofs_;` after closing the ofs_.

**Comment by RustingSword** [comment]
Thanks for pointing out, just fixed.
