### ISSUE TITLE
Outdated link to embedding projector

### ISSUE THREAD

**Issue by luggie** [RustingSword/tensorboard_logger#9]
When starting embedding projector with 
tensorboard --logdir path 
the link which appears in the console localhost:<PORT> (for me) always redicrect to http://localhost:<PORT>/# which shows an error message. Only when manually changing the link to http://localhost:PORT/#projector it works. 

This works:

```python
In [1]: import numpy as np
In [2]: np.savetxt('demo/vec.tsv', np.random.random((1000, 16)), delimiter="\t")
In [3]: np.savetxt('demo/label.tsv', np.arange(1000))
```
```bash
> ls demo
label.tsv              projector_config.pbtxt vec.tsv
> cat demo/projector_config.pbtxt
embeddings {
    tensor_path: "vec.tsv"
    metadata_path: "label.tsv"
}
> tensorboard --logdir demo
```
![projector](https://user-images.githubusercontent.com/449233/82923476-9ec39d80-9fad-11ea-8b5b-b31375d660a5.png)

_Originally posted by @RustingSword in https://github.com/RustingSword/tensorboard_logger/issues/2#issuecomment-634120800_

**Comment by RustingSword** [comment]
I can reproduce this, however I found that you don't need to change the link, just refresh the page and projector tab will appear. Maybe this is a bug in tensorboard?

**Comment by luggie** [comment]
I can confirm that the link changes to http://localhost:6006/#projector when reloading
